owner: j4lc
repo: externalmonitoring

sites:
  - name: GitLab Pages
    url: https://jae.fi
  - name: GitLab Interface
    url: https://g.j4.lc
  - name: FreshRSS
    url: https://rss.jae.fi
  - name: Blog
    url: https://b.j4.lc
  - name: PBX
    url: https://pbx.jae.fi
  - name: Vaultwarden
    url: https://bw.j4.lc
  - name: Cloud
    url: https://cloud.jae.fi
  - name: Office
    url: https://office.jae.fi
  - name: Media
    url: https://media.jae.fi
  - name: SSO
    url: https://id.j4.lc

status-website:
  # cname: status.purpletech.fi
  baseUrl: /externalmonitoring
  logoUrl: https://jae.fi/assets/img/JaeSticker01.webp
  name: Monitoring
  introTitle: "Monitoring of PurpleTech services. This freeloads GitHub as a status checker."
  introMessage: None.
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: /blog
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
